### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by jacoblockard99** [peckjon/github-to-guru#17]
When running the action, I get a, "Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16."

**Comment by peckjon** [comment]
@jacoblockard99 thanks for flagging this!

I've updated -- would you be so kind as to try [version 1.8.0](https://github.com/peckjon/github-to-guru/releases/tag/1.8.0) and let me know if it looks good?

**Comment by jacoblockard99** [comment]
Thanks! I'll try it as soon as I can and let you know.
